### ISSUE TITLE
Export sharing constants for unchanged values to a module

### ISSUE THREAD

**Issue by floalex** [WilfredTA/batnode_proto#20]
Example: Since our default port and host values will be the same and never change for the 2nd BatNode server communicating with command line. It will be convenient to to define such constants once in a module. Extracting them in a module allows us to look up these unchanged values across the project. Defining them in one place will also prevents us from having typo errors.

**Comment by WilfredTA** [comment]
Agreed. Just added this, see commit [here](https://github.com/WilfredTA/batnode_proto/commit/fcb6524f81a2a59924f68b72074bd028db62961e)
