### ISSUE TITLE
Retrieving a file from a secondary machine

### ISSUE THREAD

**Issue by wgerven** [WilfredTA/batnode_proto#57]
Great project, really learned a lot from your youtube video (https://www.youtube.com/watch?v=oCS05QSQ-1k). What isn't clear to me is the following: The use of a centralized cloud service is that when I upload on machine A, I can come online on machine B, independent of whether A is online or not, and get what A uploaded previously. However, what I don't get with Layr is that it works with a manifest file. As you show in your demo, you need to hand the CLI a path to a manifest. If I upload something on machine A, how am I getting the necessary manifest on machine B to access the uploaded file?

**Comment by dylankb** [comment]
Good question. It's been about 2 years since I touched any Layr code, but I believe that part of the how the system is designed to work is that the second machine B needs to have access to an identical manifest file. You could consider this a limitation.
